<?php
namespace Modules\LkdYoung\Http\Controllers;
use App\Http\Controllers\Controller; use App\Models\Universities; use Modules\LkdYoung\Models\{LkdYoungAnnouncement,LkdYoungApplication,LkdYoungRepresentative}; use Modules\LkdYoung\Support\InteractsWithRepresentatives; use App\Services\MailgunMailingList; use App\Support\HtmlSanitizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Mail};
class LkdYoungController extends Controller {
 use InteractsWithRepresentatives;
 public function __construct(){ $this->middleware('auth'); }
 public function getJoinLkdYoung(){ $universities=Universities::where('status',1)->orderBy('university_name')->get(); return view('lkd-young::join',compact('universities')); }
 public function postJoinLkdYoung(Request $r, MailgunMailingList $lists){$d=$r->validate(['university_id'=>['required','exists:universities,id'],'department'=>'required|max:255','education_level'=>'required|max:255','club_name'=>'nullable|max:255','club_role'=>'nullable|max:255','motivation'=>'nullable|max:4000','contact_consent'=>'accepted','wants_representative'=>'nullable|boolean']);$w=$r->boolean('wants_representative'); if($w && !$this->activeAlias($r->user())) return back()->withErrors(['wants_representative'=>'Temsilcilik için önce @'.config('mail-forwarding.domain').' e-posta yönlendirmenizi aktifleştirmelisiniz.'])->withInput(); $app=LkdYoungApplication::updateOrCreate(['user_id'=>Auth::id(),'university_id'=>$d['university_id']],array_merge($d,['wants_representative'=>$w,'contact_consent'=>true,'status'=>'active'])); $rep=LkdYoungRepresentative::with('user')->where('university_id',$d['university_id'])->where('status','active')->first(); if($rep){$this->sendIntroduction($app,$rep);if($rep->mailing_list_address)$lists->upsertMember($rep->mailing_list_address,$app->user->email,$app->user->name.' '.$app->user->surname);} if($w){LkdYoungRepresentative::updateOrCreate(['university_id'=>$d['university_id'],'user_id'=>Auth::id()],['status'=>'pending']); Mail::raw('Yeni LKD Genç temsilcilik adaylığı: '.$r->user()->email,fn($m)=>$m->to('yk@lkd.org.tr')->subject('LKD Genç temsilcilik adaylığı'));}$this->set_log('create',$w?'LKD Genç katılımı ve temsilcilik adaylığı oluşturuldu.':'LKD Genç katılımı oluşturuldu.'); return redirect()->route('join-lkd-young')->with('success-status',$rep?'Başvurunuz alındı. Temsilci iletişim bilgileri e-posta ile paylaşıldı.':'Başvurunuz alındı.'); }
 public function createAnnouncement(){ $rep=LkdYoungRepresentative::with('university')->where('user_id',Auth::id())->where('status','active')->firstOrFail();return view('lkd-young::announcement_form',compact('rep')); }
 public function storeAnnouncement(Request $r){$rep=LkdYoungRepresentative::where('user_id',Auth::id())->where('status','active')->firstOrFail();$d=$r->validate(['subject'=>'required|max:255','detail'=>'required|max:20000']);$a=LkdYoungAnnouncement::create(['university_id'=>$rep->university_id,'representative_id'=>$rep->id,'created_by'=>Auth::id(),'subject'=>$d['subject'],'detail'=>app(HtmlSanitizer::class)->sanitize($d['detail']),'status'=>$rep->can_send_announcements?'approved':'pending']);if($a->status==='approved')$this->sendAnnouncement($a,$rep);else Mail::raw('LKD Genç duyurusu onay bekliyor: '.$a->subject,fn($m)=>$m->to('yk@lkd.org.tr')->subject('LKD Genç duyuru onayı'));return redirect()->route('lkd-young.announcements')->with('success-status',$a->status==='pending'?'Duyuru YK onayına gönderildi.':'Duyuru gönderildi.'); }
 public function announcements(){ $rep=LkdYoungRepresentative::where('user_id',Auth::id())->where('status','active')->first();$q=LkdYoungAnnouncement::with('university')->latest();if(! Auth::user()->isOwner()){if(!$rep)abort(403);$q->where('university_id',$rep->university_id);}return view('lkd-young::announcements',['announcements'=>$q->get()]); }
 private function sendIntroduction($app,$rep){$alias=$this->activeAlias($rep->user);if(!$alias)return;Mail::raw('Yeni LKD Genç katılımcısı: '.$app->user->name.' '.$app->user->surname.'; E-posta: '.$app->user->email.'; Telefon: '.$app->user->phone_number,fn($m)=>$m->to($alias->email_alias)->subject('Yeni LKD Genç katılımcısı'));Mail::raw('Üniversitenizdeki LKD Genç temsilcisi: '.$rep->user->name.' '.$rep->user->surname.'; E-posta: '.$alias->email_alias.'; Telefon: '.$rep->user->phone_number,fn($m)=>$m->to($app->user->email)->subject('LKD Genç temsilci iletişim bilgileri'));}
}
