<?php
namespace Modules\LkdYoung\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\Universities; use Modules\LkdYoung\Models\{LkdYoungAnnouncement,LkdYoungApplication,LkdYoungRepresentative}; use Modules\LkdYoung\Support\InteractsWithRepresentatives; use App\Services\MailgunMailingList; use App\Support\HtmlSanitizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Mail};
class LkdYoungController extends Controller {
 use InteractsWithRepresentatives;
 public function admin(){return view('lkd-young::admin.index',['applications'=>LkdYoungApplication::with(['user','university'])->latest()->get(),'representatives'=>LkdYoungRepresentative::with(['user','university'])->latest()->get()]);}
 public function approveRepresentative(LkdYoungRepresentative $rep,MailgunMailingList $lists){if(LkdYoungRepresentative::where('university_id',$rep->university_id)->where('status','active')->where('id','!=',$rep->id)->exists())return back()->with('danger-status','Bu üniversitenin zaten aktif temsilcisi var.');if(!$this->activeAlias($rep->user))return back()->with('danger-status','Adayın aktif e-posta yönlendirmesi yok.');$domain=config('services.mailgun.lists_domain');if(!$domain)return back()->with('danger-status','MAILGUN_LISTS_DOMAIN yapılandırılmamış.');$address='lkd-genc-university-'.$rep->university_id.'@'.$domain;if(!$lists->ensure($address,'LKD Genç '.$rep->university->university_name))return back()->with('danger-status','Mailgun listesi oluşturulamadı.');$rep->update(['status'=>'active','approved_at'=>now(),'approved_by'=>Auth::id(),'mailing_list_address'=>$address]);foreach(LkdYoungApplication::with('user')->where('university_id',$rep->university_id)->where('contact_consent',true)->get() as $a)$lists->upsertMember($address,$a->user->email,$a->user->name.' '.$a->user->surname);$alias=$this->activeAlias($rep->user);$lists->upsertMember($address,$alias->email_alias,$rep->user->name.' '.$rep->user->surname);$this->set_log('change','LKD Genç temsilcisi onaylandı ve Mailgun listesi oluşturuldu.');return back()->with('success-status','Temsilci onaylandı ve üniversite listesi oluşturuldu.');}
 public function rejectRepresentative(LkdYoungRepresentative $rep){$rep->update(['status'=>'rejected','approved_by'=>Auth::id(),'approved_at'=>now()]);$this->set_log('change','LKD Genç temsilci adaylığı reddedildi.');return back()->with('success-status','Adaylık reddedildi.');}
 public function setAnnouncementPermission(Request $r,LkdYoungRepresentative $rep){$rep->update(['can_send_announcements'=>$r->boolean('can_send_announcements')]);$this->set_log('change','LKD Genç temsilcisi duyuru yetkisi güncellendi.');return back();}
 public function approveAnnouncement(LkdYoungAnnouncement $a){$rep=LkdYoungRepresentative::where('university_id',$a->university_id)->where('status','active')->firstOrFail();$a->update(['status'=>'approved','approved_by'=>Auth::id()]);$this->sendAnnouncement($a,$rep);$this->set_log('change','LKD Genç duyurusu onaylandı.');return back()->with('success-status','Duyuru gönderildi.');}
}
