@extends($inIframe ? 'layouts.iframe' : 'layouts.app')
@section('content')
<div class="container"><div class="row justify-content-center"><div class="col-md-9"><div class="card border-secondary"><div class="card-header text-white bg-secondary">Seminer Vermek İstiyorum</div><div class="card-body">
@if(session('success-status'))<div class="alert alert-success">{{ session('success-status') }}</div>@endif
<p>Başvuru formunu doldurabilirsiniz. Gönderim aşamasında üyelik veya giriş gereklidir; iletişim bilgileriniz üyelik kaydınızdan alınır.</p>
<form method="POST" action="{{ route('seminar-offer.store', $inIframe ? ['in-iframe' => 1] : []) }}">@csrf
<div class="mb-3"><label class="form-label">Konu</label><div class="form-check"><input class="form-check-input subject-choice" type="radio" name="subject_choice" value="existing" id="subject_existing" @checked(old('subject_choice', $formData['subject_choice'] ?? 'existing') === 'existing')><label class="form-check-label" for="subject_existing">Seminer havuzundan seç</label></div><div class="form-check"><input class="form-check-input subject-choice" type="radio" name="subject_choice" value="proposed" id="subject_proposed" @checked(old('subject_choice', $formData['subject_choice'] ?? '') === 'proposed')><label class="form-check-label" for="subject_proposed">Yeni konu öner</label></div></div>
<div class="mb-3" id="existing-subject"><select name="seminar_subject_id" class="form-select @error('seminar_subject_id') is-invalid @enderror"><option value="">Seminer seçin</option>@foreach($seminarSubjects as $subject)<option value="{{ $subject->id }}" @selected(old('seminar_subject_id', $formData['seminar_subject_id'] ?? '') == $subject->id)>{{ $subject->subject }}</option>@endforeach</select>@error('seminar_subject_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3 d-none" id="proposed-subject"><input name="proposed_subject" value="{{ old('proposed_subject', $formData['proposed_subject'] ?? '') }}" class="form-control @error('proposed_subject') is-invalid @enderror" placeholder="Önerdiğiniz seminer konusu">@error('proposed_subject')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label">Kısa özet</label><textarea name="summary" class="form-control" required>{{ old('summary', $formData['summary'] ?? '') }}</textarea></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Hedef kitle</label><input name="target_audience" value="{{ old('target_audience', $formData['target_audience'] ?? '') }}" class="form-control" required></div><div class="col-md-6 mb-3"><label class="form-label">Tahmini süre (saat)</label><input type="number" min="1" max="48" name="duration" value="{{ old('duration', $formData['duration'] ?? '') }}" class="form-control" required></div></div>
<div class="mb-3"><label class="form-label">Sunum türü</label><select name="seminar_type" class="form-select" required><option value="in_person" @selected(old('seminar_type', $formData['seminar_type'] ?? '') === 'in_person')>Yüz yüze</option><option value="online" @selected(old('seminar_type', $formData['seminar_type'] ?? '') === 'online')>Online</option><option value="either" @selected(old('seminar_type', $formData['seminar_type'] ?? 'either') === 'either')>Fark etmez</option></select></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Uygunluk başlangıcı</label><input type="date" name="availability_start_date" value="{{ old('availability_start_date', $formData['availability_start_date'] ?? '') }}" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label">Uygunluk bitişi</label><input type="date" name="availability_end_date" value="{{ old('availability_end_date', $formData['availability_end_date'] ?? '') }}" class="form-control"></div></div>
<div class="mb-3"><label class="form-label">Uygun şehirler</label><input name="cities" value="{{ old('cities', $formData['cities'] ?? '') }}" class="form-control"></div><div class="mb-3"><label class="form-label">Teknik gereksinimler</label><textarea name="technical_requirements" class="form-control">{{ old('technical_requirements', $formData['technical_requirements'] ?? '') }}</textarea></div>
<div class="mb-3"><label class="form-label">Özgeçmiş</label><textarea name="biography" class="form-control" rows="7" required>{{ old('biography', $formData['biography'] ?? '') }}</textarea></div><div class="mb-3"><label class="form-label">Referans bağlantıları</label><textarea name="reference_links" class="form-control">{{ old('reference_links', $formData['reference_links'] ?? '') }}</textarea></div><div class="mb-3"><label class="form-label">Ek notlar</label><textarea name="notes" class="form-control">{{ old('notes', $formData['notes'] ?? '') }}</textarea></div><button class="btn btn-primary">Başvuruyu gönder</button>
</form></div></div></div></div></div>
<script>const syncSubjectChoice=()=>{const p=document.querySelector('#subject_proposed').checked;document.querySelector('#existing-subject').classList.toggle('d-none',p);document.querySelector('#proposed-subject').classList.toggle('d-none',!p)};document.querySelectorAll('.subject-choice').forEach(e=>e.addEventListener('change',syncSubjectChoice));syncSubjectChoice();</script>
@endsection
