<?php
namespace Modules\Representation\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use Modules\Representation\Models\{LegalRepresentation,LegalRepresentationAnnouncement,LegalRepresentationCandidate,LegalRepresentationVolunteer}; use Modules\Representation\Support\SendsAnnouncements; use App\Services\MailgunMailingList; use App\Support\HtmlSanitizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Mail};
class LegalRepresentationController extends Controller {
 use SendsAnnouncements;
 public function admin(){return view('representation::admin.index',['representations'=>LegalRepresentation::with('user')->get(),'candidates'=>LegalRepresentationCandidate::with(['representation','user'])->latest()->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get(['id','name','surname','email'])]);}
 public function edit(LegalRepresentation $representation){return view('representation::admin.edit',['representation'=>$representation,'users'=>\App\Models\User::where('status',1)->orderBy('name')->get(['id','name','surname','email'])]);}
 public function update(Request $r,LegalRepresentation $representation){$d=$r->validate(['representative_name'=>'required|max:255','email'=>'required|email|max:255','address'=>'required|max:5000','user_id'=>'nullable|exists:users,id','can_send_announcements'=>'nullable|boolean']);$representation->update(array_merge($d,['can_send_announcements'=>$r->boolean('can_send_announcements')]));$this->set_log('change',"{$representation->city} temsilciliği düzenlendi.");return redirect()->route('admin.representations')->with('success-status','Temsilcilik bilgileri güncellendi.');}
 public function assignUser(Request $r,LegalRepresentation $representation){$d=$r->validate(['user_id'=>'nullable|exists:users,id']);$representation->update(['user_id'=>$d['user_id'] ?? null]);$this->set_log('change',"{$representation->city} temsilciliğine sistem kullanıcısı atandı.");return back()->with('success-status','Temsilcilik kullanıcı ataması güncellendi.');}
 public function approveCandidate(LegalRepresentationCandidate $candidate,MailgunMailingList $lists){if($candidate->status!=='pending')return back();$rep=$candidate->representation;$address='lkd-temsilcilik-'.$rep->id.'@'.config('services.mailgun.lists_domain');if(!config('services.mailgun.lists_domain')||!$lists->ensure($address,'LKD Temsilcilik '.$rep->city))return back()->with('danger-status','Mailgun listesi oluşturulamadı.');$rep->update(['user_id'=>$candidate->user_id,'representative_name'=>$candidate->user->name.' '.$candidate->user->surname,'mailing_list_address'=>$address]);$candidate->update(['status'=>'approved','processed_by'=>Auth::id(),'processed_at'=>now()]);$lists->upsertMember($address,$candidate->user->email,$rep->representative_name);$this->set_log('change',"{$rep->city} temsilci adaylığı onaylandı ve liste oluşturuldu.");return back()->with('success-status','Aday onaylandı.');}
 public function rejectCandidate(LegalRepresentationCandidate $candidate){$candidate->update(['status'=>'rejected','processed_by'=>Auth::id(),'processed_at'=>now()]);$this->set_log('change','Temsilci adaylığı reddedildi.');return back()->with('success-status','Adaylık reddedildi.');}
 public function setAnnouncementPermission(Request $r,LegalRepresentation $representation){$representation->update(['can_send_announcements'=>$r->boolean('can_send_announcements')]);$this->set_log('change',"{$representation->city} duyuru yetkisi güncellendi.");return back();}
 public function approveAnnouncement(LegalRepresentationAnnouncement $announcement){$announcement->update(['status'=>'approved','approved_by'=>Auth::id()]);$this->send($announcement);$this->set_log('change','Temsilcilik duyurusu onaylandı.');return back();}
}
