<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('legal_representations',function(Blueprint $t){$t->id();$t->string('city')->unique();$t->string('representative_name');$t->string('email');$t->text('address');$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->boolean('can_send_announcements')->default(false);$t->string('mailing_list_address')->nullable();$t->boolean('status')->default(true);$t->timestamps();});
Schema::create('legal_representation_volunteers',function(Blueprint $t){$t->id();$t->foreignId('legal_representation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->boolean('contact_consent')->default(false);$t->timestamp('notified_at')->nullable();$t->timestamps();$t->unique(['legal_representation_id','user_id']);});
Schema::create('legal_representation_candidates',function(Blueprint $t){$t->id();$t->foreignId('legal_representation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->boolean('is_lkd_member');$t->string('membership_number')->nullable();$t->string('local_area');$t->text('motivation');$t->text('community_experience')->nullable();$t->string('availability')->nullable();$t->string('club_name')->nullable();$t->boolean('contact_consent')->default(false);$t->string('status')->default('pending');$t->foreignId('processed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('processed_at')->nullable();$t->timestamps();});
Schema::create('legal_representation_announcements',function(Blueprint $t){$t->id();$t->foreignId('legal_representation_id')->constrained()->cascadeOnDelete();$t->foreignId('created_by')->constrained('users')->cascadeOnDelete();$t->string('subject');$t->longText('detail');$t->string('status')->default('pending');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('sent_at')->nullable();$t->text('failure_reason')->nullable();$t->timestamps();});
DB::table('legal_representations')->upsert([['city'=>'Antalya','representative_name'=>'Ahmet Bardakcı','email'=>'ahmetbardakci@lkd.org.tr','address'=>'Kışla Mh. Milli Egemenlik Cd. Bakibey Ap. No:12/3 Kat:1 D:1 Muratpaşa / Antalya','created_at'=>now(),'updated_at'=>now()],['city'=>'Çanakkale','representative_name'=>'Cumali Yaşar','email'=>'cumaliyasar@lkd.org.tr','address'=>'Çanakkale 18 Mart Üniversitesi Anafartalar Kampüsü Eğitim Fakültesi B2 Blok Zemin Kat Odano 8 17000 Merkez/Çanakkale','created_at'=>now(),'updated_at'=>now()],['city'=>'Ordu','representative_name'=>'Kerem Erzurumlu','email'=>'keremerzurumlu@lkd.org.tr','address'=>'Akyazı Mah. 15 Temmuz Milli İrade Cad. Çiğdem Sok. No:9 Altınordu / Ordu','created_at'=>now(),'updated_at'=>now()]],['city'],['representative_name','email','address','updated_at']);
} public function down(): void {Schema::dropIfExists('legal_representation_announcements');Schema::dropIfExists('legal_representation_candidates');Schema::dropIfExists('legal_representation_volunteers');Schema::dropIfExists('legal_representations');}};
