<?php
namespace App\Http\Controllers;
use App\Models\{LegalRepresentation,LegalRepresentationAnnouncement,LegalRepresentationCandidate,LegalRepresentationVolunteer}; use App\Services\MailgunMailingList; use App\Support\HtmlSanitizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Mail};
class LegalRepresentationController extends Controller {
 public function index(){return view('representations.index',['representations'=>LegalRepresentation::where('status',true)->orderBy('city')->get()]);}
 public function consent(LegalRepresentation $representation){return view('representations.consent',compact('representation'));}
 public function storeConsent(Request $r,LegalRepresentation $representation){$r->validate(['contact_consent'=>'accepted']);$v=LegalRepresentationVolunteer::firstOrNew(['legal_representation_id'=>$representation->id,'user_id'=>Auth::id()]);$v->contact_consent=true;$v->save();if(!$v->notified_at){$u=$r->user();Mail::raw("Yeni gönüllü: {$u->name} {$u->surname}\nE-posta: {$u->email}\nTelefon: {$u->phone_number}",fn($m)=>$m->to($representation->email)->subject('Temsilcilik gönüllüsü'));Mail::raw("{$representation->city} temsilcisi: {$representation->representative_name}\nE-posta: {$representation->email}",fn($m)=>$m->to($u->email)->subject('Temsilcilik iletişim bilgileri'));$v->update(['notified_at'=>now()]);}$this->set_log('create',"{$representation->city} temsilciliği ile iletişim paylaşımı onaylandı.");return redirect()->route('representations.index')->with('success-status','İletişim bilgileriniz karşılıklı olarak paylaşıldı.');}
 public function candidateForm(){return view('representations.candidate',['representations'=>LegalRepresentation::where('status',true)->orderBy('city')->get()]);}
 public function storeCandidate(Request $r){$d=$r->validate(['legal_representation_id'=>'required|exists:legal_representations,id','is_lkd_member'=>'required|boolean','membership_number'=>'nullable|max:100','local_area'=>'required|max:255','motivation'=>'required|max:5000','community_experience'=>'nullable|max:5000','availability'=>'nullable|max:255','club_name'=>'nullable|max:255','contact_consent'=>'accepted']);LegalRepresentationCandidate::updateOrCreate(['legal_representation_id'=>$d['legal_representation_id'],'user_id'=>Auth::id(),'status'=>'pending'],$d);Mail::raw('Yeni yasal temsilci adaylığı: '.$r->user()->email,fn($m)=>$m->to('yk@lkd.org.tr')->subject('Temsilci adaylığı'));$this->set_log('create','Yasal temsilcilik adaylığı oluşturuldu.');return back()->with('success-status','Adaylığınız YK değerlendirmesine gönderildi.');}
 public function admin(){return view('admin.representations',['representations'=>LegalRepresentation::with('user')->get(),'candidates'=>LegalRepresentationCandidate::with(['representation','user'])->latest()->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get(['id','name','surname','email'])]);}
 public function edit(LegalRepresentation $representation){return view('admin.representation_edit',['representation'=>$representation,'users'=>\App\Models\User::where('status',1)->orderBy('name')->get(['id','name','surname','email'])]);}
 public function update(Request $r,LegalRepresentation $representation){$d=$r->validate(['representative_name'=>'required|max:255','email'=>'required|email|max:255','address'=>'required|max:5000','user_id'=>'nullable|exists:users,id','can_send_announcements'=>'nullable|boolean']);$representation->update(array_merge($d,['can_send_announcements'=>$r->boolean('can_send_announcements')]));$this->set_log('change',"{$representation->city} temsilciliği düzenlendi.");return redirect()->route('admin.representations')->with('success-status','Temsilcilik bilgileri güncellendi.');}
 public function assignUser(Request $r,LegalRepresentation $representation){$d=$r->validate(['user_id'=>'nullable|exists:users,id']);$representation->update(['user_id'=>$d['user_id'] ?? null]);$this->set_log('change',"{$representation->city} temsilciliğine sistem kullanıcısı atandı.");return back()->with('success-status','Temsilcilik kullanıcı ataması güncellendi.');}
 public function approveCandidate(LegalRepresentationCandidate $candidate,MailgunMailingList $lists){if($candidate->status!=='pending')return back();$rep=$candidate->representation;$address='lkd-temsilcilik-'.$rep->id.'@'.config('services.mailgun.lists_domain');if(!config('services.mailgun.lists_domain')||!$lists->ensure($address,'LKD Temsilcilik '.$rep->city))return back()->with('danger-status','Mailgun listesi oluşturulamadı.');$rep->update(['user_id'=>$candidate->user_id,'representative_name'=>$candidate->user->name.' '.$candidate->user->surname,'mailing_list_address'=>$address]);$candidate->update(['status'=>'approved','processed_by'=>Auth::id(),'processed_at'=>now()]);$lists->upsertMember($address,$candidate->user->email,$rep->representative_name);$this->set_log('change',"{$rep->city} temsilci adaylığı onaylandı ve liste oluşturuldu.");return back()->with('success-status','Aday onaylandı.');}
 public function rejectCandidate(LegalRepresentationCandidate $candidate){$candidate->update(['status'=>'rejected','processed_by'=>Auth::id(),'processed_at'=>now()]);$this->set_log('change','Temsilci adaylığı reddedildi.');return back()->with('success-status','Adaylık reddedildi.');}
 public function setAnnouncementPermission(Request $r,LegalRepresentation $representation){$representation->update(['can_send_announcements'=>$r->boolean('can_send_announcements')]);$this->set_log('change',"{$representation->city} duyuru yetkisi güncellendi.");return back();}
 public function announcements(){ $rep=LegalRepresentation::where('user_id',Auth::id())->firstOrFail();return view('representations.announcements',['rep'=>$rep,'announcements'=>LegalRepresentationAnnouncement::where('legal_representation_id',$rep->id)->latest()->get()]);}
 public function storeAnnouncement(Request $r){$rep=LegalRepresentation::where('user_id',Auth::id())->firstOrFail();$d=$r->validate(['subject'=>'required|max:255','detail'=>'required|max:20000']);$a=LegalRepresentationAnnouncement::create(['legal_representation_id'=>$rep->id,'created_by'=>Auth::id(),'subject'=>$d['subject'],'detail'=>app(HtmlSanitizer::class)->sanitize($d['detail']),'status'=>$rep->can_send_announcements?'approved':'pending']);if($a->status==='approved')$this->send($a);else Mail::raw('Temsilcilik duyurusu onay bekliyor: '.$a->subject,fn($m)=>$m->to('yk@lkd.org.tr')->subject('Temsilcilik duyuru onayı'));$this->set_log('create',"{$rep->city} duyurusu oluşturuldu.");return back()->with('success-status','Duyuru kaydedildi.');}
 public function approveAnnouncement(LegalRepresentationAnnouncement $announcement){$announcement->update(['status'=>'approved','approved_by'=>Auth::id()]);$this->send($announcement);$this->set_log('change','Temsilcilik duyurusu onaylandı.');return back();}
 private function send($a){try{Mail::to($a->representation->mailing_list_address)->send(new \App\Mail\AnnouncementMailing((object)['subject'=>$a->subject,'content'=>$a->detail]));$a->update(['status'=>'sent','sent_at'=>now()]);}catch(\Throwable $e){$a->update(['status'=>'failed','failure_reason'=>$e->getMessage()]);}}
}
