<?php
namespace Modules\Representation\Http\Controllers;
use App\Http\Controllers\Controller; use Modules\Representation\Models\{LegalRepresentation,LegalRepresentationAnnouncement,LegalRepresentationCandidate,LegalRepresentationVolunteer}; use Modules\Representation\Support\SendsAnnouncements; use App\Services\MailgunMailingList; use App\Support\HtmlSanitizer; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Mail};
class LegalRepresentationController extends Controller {
 use SendsAnnouncements;
 public function index(){return view('representation::index',['representations'=>LegalRepresentation::where('status',true)->orderBy('city')->get()]);}
 public function consent(LegalRepresentation $representation){return view('representation::consent',compact('representation'));}
 public function storeConsent(Request $r,LegalRepresentation $representation){$r->validate(['contact_consent'=>'accepted']);$v=LegalRepresentationVolunteer::firstOrNew(['legal_representation_id'=>$representation->id,'user_id'=>Auth::id()]);$v->contact_consent=true;$v->save();if(!$v->notified_at){$u=$r->user();try{Mail::raw("Yeni gönüllü: {$u->name} {$u->surname}\nE-posta: {$u->email}\nTelefon: {$u->phone_number}",fn($m)=>$m->to($representation->email)->subject('Temsilcilik gönüllüsü'));Mail::raw("{$representation->city} temsilcisi: {$representation->representative_name}\nE-posta: {$representation->email}",fn($m)=>$m->to($u->email)->subject('Temsilcilik iletişim bilgileri'));$v->update(['notified_at'=>now()]);}catch(\Throwable $e){report($e);}}$this->set_log('create',"{$representation->city} temsilciliği ile iletişim paylaşımı onaylandı.");return redirect()->route('representations.index')->with('success-status','İletişim bilgileriniz karşılıklı olarak paylaşıldı.');}
 public function candidateForm(){return view('representation::candidate',['representations'=>LegalRepresentation::where('status',true)->orderBy('city')->get()]);}
 public function storeCandidate(Request $r){$d=$r->validate(['legal_representation_id'=>'required|exists:legal_representations,id','is_lkd_member'=>'required|boolean','membership_number'=>'nullable|max:100','local_area'=>'required|max:255','motivation'=>'required|max:5000','community_experience'=>'nullable|max:5000','availability'=>'nullable|max:255','club_name'=>'nullable|max:255','contact_consent'=>'accepted']);LegalRepresentationCandidate::updateOrCreate(['legal_representation_id'=>$d['legal_representation_id'],'user_id'=>Auth::id(),'status'=>'pending'],$d);Mail::raw('Yeni yasal temsilci adaylığı: '.$r->user()->email,fn($m)=>$m->to('yk@lkd.org.tr')->subject('Temsilci adaylığı'));$this->set_log('create','Yasal temsilcilik adaylığı oluşturuldu.');return back()->with('success-status','Adaylığınız YK değerlendirmesine gönderildi.');}
 public function announcements(){ $rep=LegalRepresentation::where('user_id',Auth::id())->firstOrFail();return view('representation::announcements',['rep'=>$rep,'announcements'=>LegalRepresentationAnnouncement::where('legal_representation_id',$rep->id)->latest()->get()]);}
 public function storeAnnouncement(Request $r){$rep=LegalRepresentation::where('user_id',Auth::id())->firstOrFail();$d=$r->validate(['subject'=>'required|max:255','detail'=>'required|max:20000']);$a=LegalRepresentationAnnouncement::create(['legal_representation_id'=>$rep->id,'created_by'=>Auth::id(),'subject'=>$d['subject'],'detail'=>app(HtmlSanitizer::class)->sanitize($d['detail']),'status'=>$rep->can_send_announcements?'approved':'pending']);if($a->status==='approved')$this->send($a);else Mail::raw('Temsilcilik duyurusu onay bekliyor: '.$a->subject,fn($m)=>$m->to('yk@lkd.org.tr')->subject('Temsilcilik duyuru onayı'));$this->set_log('create',"{$rep->city} duyurusu oluşturuldu.");return back()->with('success-status','Duyuru kaydedildi.');}
}
